name: "Agentic Decision Ledger Gate"
description: "Commit-time decision admissibility gate + artifact emission"
author: "agentic-decision-ledger"

inputs:
  contract:
    description: "Single Decision Contract path (optional). If set, overrides autodetection."
    required: false
    default: ""

  maintenance-contract:
    description: "Contract for self-governance / repo maintenance (bootstrap posture)."
    required: false
    default: "decisions/contracts/DC-REPO-001.yaml"

  install-demo-contract:
    description: "Docs-only install demo posture (target repos)."
    required: false
    default: "decisions/contracts/DC-INSTALL-DEMO-001.yaml"

  example-contract:
    description: "Example/demo posture (optional fallback when not maintenance and not docs-only)."
    required: false
    default: "decisions/contracts/DC-2026-001.yaml"

  strict:
    description: "Strict mode blocks on warnings and schema issues."
    required: false
    default: "true"

  artifacts-dir:
    description: "Directory to write artifacts."
    required: false
    default: "artifacts"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install agentic-decision-ledger
      shell: bash
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"

    - name: Determine governing contract (install vs maintenance)
      id: contract
      shell: bash
      run: |
        set -euo pipefail

        INPUT_CONTRACT="${{ inputs.contract }}"
        MAINT="${{ inputs.maintenance-contract }}"
        INSTALL="${{ inputs.install-demo-contract }}"
        EXAMPLE="${{ inputs.example-contract }}"

        # 1) Explicit override
        if [ -n "${INPUT_CONTRACT:-}" ]; then
          echo "contract=$INPUT_CONTRACT" >> "$GITHUB_OUTPUT"
          echo "route=explicit" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # 2) Compute diff (PR base->head, else last commit)
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.sha }}"

        if [ -z "${BASE_SHA:-}" ]; then
          BASE_SHA="$(git rev-parse HEAD~1 2>/dev/null || true)"
        fi

        CHANGED=""
        if [ -n "${BASE_SHA:-}" ]; then
          CHANGED="$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" || true)"
        fi

        echo "changed_paths<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CHANGED" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        # If we can't detect diffs, default to maintenance (safest posture)
        if [ -z "${CHANGED:-}" ]; then
          echo "No changed paths detected; routing to maintenance contract: $MAINT"
          echo "contract=$MAINT" >> "$GITHUB_OUTPUT"
          echo "route=fallback_maintenance_no_diff" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # 3) Maintenance posture triggers (this repo is the product/control-plane)
        # Treat README/docs/examples/scripts/contracts as maintenance because they define the control plane product.
        if echo "$CHANGED" | grep -Eq '^(README\.md|docs/|examples/|scripts/|decisions/contracts/|\.github/workflows/|integrations/github-action/|adl/|pyproject\.toml|tests/)'; then
          echo "Maintenance surface change detected; routing to maintenance contract: $MAINT"
          echo "contract=$MAINT" >> "$GITHUB_OUTPUT"
          echo "route=maintenance" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # 4) Install demo posture: docs/artifacts only (target repos)
        # If ANY changed path is outside docs/ or artifacts/, it's not install-demo.
        if echo "$CHANGED" | grep -Eq '^(docs/|artifacts/)' && ! echo "$CHANGED" | grep -Eq '^(docs/|artifacts/)$' && ! echo "$CHANGED" | grep -Eq '^(docs/|artifacts/)'; then
          # unreachable guard (kept intentionally empty)
          :
        fi

        if ! echo "$CHANGED" | grep -Eq '^(docs/|artifacts/)'; then
          : # not docs-only
        else
          # ensure ALL lines match docs/ or artifacts/
          if echo "$CHANGED" | grep -Evq '^(docs/|artifacts/)'; then
            : # not docs-only
          else
            echo "Docs-only change detected; routing to install demo contract: $INSTALL"
            echo "contract=$INSTALL" >> "$GITHUB_OUTPUT"
            echo "route=install_demo" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi

        # 5) Fallback: example/demo contract
        echo "Routing to example/demo contract: $EXAMPLE"
        echo "contract=$EXAMPLE" >> "$GITHUB_OUTPUT"
        echo "route=example_demo_fallback" >> "$GITHUB_OUTPUT"
        exit 0

    - name: Run admissibility gate (record + artifacts)
      shell: bash
      run: |
        set -euo pipefail

        STRICT="${{ inputs.strict }}"
        ART_DIR="${{ inputs.artifacts-dir }}"
        CONTRACT="${{ steps.contract.outputs.contract }}"
        ROUTE="${{ steps.contract.outputs.route }}"

        echo "Route: $ROUTE"
        echo "Evaluating contract: $CONTRACT"

        if [ "$STRICT" = "true" ]; then
          adl record --contract "$CONTRACT" --strict --artifacts-dir "$ART_DIR"
        else
          adl record --contract "$CONTRACT" --non-strict --artifacts-dir "$ART_DIR"
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: adl-artifacts
        path: |
          artifacts/decision_records/
          artifacts/snapshots/
