name: "Agentic Decision Ledger Gate"
description: "Commit-time decision admissibility gate: validate contract, evaluate boundaries, emit artifacts."

inputs:
  contract:
    description: "Path to Decision Contract YAML"
    required: true
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
  artifacts-dir:
    description: "Artifacts output directory"
    required: false
    default: "artifacts"
  strict:
    description: "Strict mode: block on warnings"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install package
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install .[dev]

    - name: Run admissibility gate (record)
      shell: bash
      run: |
        if [ "${{ inputs.strict }}" = "true" ]; then
          adl record --contract "${{ inputs.contract }}" --artifacts-dir "${{ inputs.artifacts-dir }}" --strict
        else
          adl record --contract "${{ inputs.contract }}" --artifacts-dir "${{ inputs.artifacts-dir }}" --non-strict
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: adl-artifacts
        path: ${{ inputs.artifacts-dir }}
