name: "Agentic Decision Ledger Gate"
description: "Commit-time decision admissibility gate + artifact emission"
author: "agentic-decision-ledger"

inputs:
  contract:
    description: "Single Decision Contract path (optional). If set, overrides autodetection."
    required: false
    default: ""

  contracts-glob:
    description: "Glob to search decision contracts for autodetection."
    required: false
    default: "decisions/contracts/**/*.yaml"

  maintenance-contract:
    description: "Contract for self-governance / repo maintenance (bootstrap posture)."
    required: false
    default: "decisions/contracts/DC-REPO-001.yaml"

  strict:
    description: "Strict mode blocks on warnings and schema issues."
    required: false
    default: "true"

  artifacts-dir:
    description: "Directory to write artifacts."
    required: false
    default: "artifacts"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install agentic-decision-ledger
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"

    - name: Determine contracts to evaluate (route install vs maintenance)
      id: contracts
      shell: bash
      run: |
        set -euo pipefail

        INPUT_CONTRACT="${{ inputs.contract }}"
        MAINT="${{ inputs.maintenance-contract }}"

        # 1) Explicit override
        if [ -n "$INPUT_CONTRACT" ]; then
          echo "contracts=$INPUT_CONTRACT" >> "$GITHUB_OUTPUT"
          echo "route=explicit" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.sha }}"

        # If not a PR, fall back to "last commit" diff
        if [ -z "${BASE_SHA:-}" ]; then
          BASE_SHA="$(git rev-parse HEAD~1 2>/dev/null || echo '')"
        fi

        CHANGED=""
        if [ -n "${BASE_SHA:-}" ]; then
          CHANGED="$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" || true)"
        fi

        echo "changed_paths<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CHANGED" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        # 2) Governance paths mean "maintenance posture"
        # These are the paths that define or enforce governance itself.
        GOVERNANCE_REGEX='^(\.github/workflows/|integrations/github-action/|adl/engine/|adl/schema/|pyproject\.toml|tests/)'

        if echo "$CHANGED" | grep -Eq "$GOVERNANCE_REGEX"; then
          echo "Governance change detected. Routing to maintenance contract: $MAINT"
          echo "contracts=$MAINT" >> "$GITHUB_OUTPUT"
          echo "route=maintenance" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # 3) Otherwise: run any changed decision contracts, else fallback to maintenance
        CHANGED_CONTRACTS="$(echo "$CHANGED" | grep -E '^decisions/contracts/.*\.ya?ml$' || true)"

        if [ -z "$CHANGED_CONTRACTS" ]; then
          echo "No contract files changed. Falling back to maintenance contract: $MAINT"
          echo "contracts=$MAINT" >> "$GITHUB_OUTPUT"
          echo "route=fallback_maintenance" >> "$GITHUB_OUTPUT"
        else
          echo "Changed contracts:"
          echo "$CHANGED_CONTRACTS"
          echo "contracts=$(echo "$CHANGED_CONTRACTS" | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          echo "route=changed_contracts" >> "$GITHUB_OUTPUT"
        fi

    - name: Run admissibility gate (record + artifacts)
      shell: bash
      run: |
        set -euo pipefail
        STRICT="${{ inputs.strict }}"
        ART_DIR="${{ inputs.artifacts-dir }}"
        CONTRACTS="${{ steps.contracts.outputs.contracts }}"
        ROUTE="${{ steps.contracts.outputs.route }}"

        echo "Route: $ROUTE"
        echo "Evaluating contracts: $CONTRACTS"

        for c in $CONTRACTS; do
          echo "==> adl record --contract $c"
          if [ "$STRICT" = "true" ]; then
            adl record --contract "$c" --strict --artifacts-dir "$ART_DIR"
          else
            adl record --contract "$c" --non-strict --artifacts-dir "$ART_DIR"
          fi
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: adl-artifacts
        path: |
          artifacts/decision_records/
          artifacts/snapshots/
